### PR TITLE
a PR for doing a code review!

### PR DESCRIPTION
**Pull request by aryarm**
This PR serves no purpose other than to allow me to review your code using Github's code-review feature.

Expect comments soon!

### CODE REVIEW

**Review by aryarm — COMMENTED** [review]
- is it possible for [a phenotype field name to include an underscore](https://github.com/LiterallyUniqueLogin/ukbiobank_strs/pull/1/files?diff=unified&w=0#diff-6c0c4fb57b3df01ca1ec0d8dffcdd1e24e77f0d7f3414a7ca430364d365949acR62)? if so, you might have problems b/c you tend to separate your wildcards by underscores. You can minimize the risk of wildcards getting misunderstood by separating your wildcards with `/`, `.`, or `-`.
- just my personal preference: I like to use `expand()` whenever possible. I think it makes for cleaner code, makes it easier to understand at a glance when I'm referring to the output of a different rule, and makes it clear how my variables get translated into wildcards. For example, [this section](https://github.com/LiterallyUniqueLogin/ukbiobank_strs/pull/1/files?diff=unified&w=0#diff-6c0c4fb57b3df01ca1ec0d8dffcdd1e24e77f0d7f3414a7ca430364d365949acR81-R85) could instead be
    ```
        fields.extend(
            expand(
                rules.decompress_field.output[0], zip, 
                field_name = ['year_of_birth', 'month_of_birth', 'date_of_death'],
                field_id = ['34', '52', '40000']
            )
        )
    ```
    It might not improve the clarity of the code as much in this specific example, but it might be something to consider for more complicated situations in which you have lots of wildcards and lots of variables.
- By the way, it seems like you're already starting to do this, but I would just recommend [naming all of your input and output files](https://snakemake.readthedocs.io/en/stable/snakefiles/rules.html) so that you can access them by their name keyword (ex: `rules.decompress_field.output.readme` instead of `rules.decompress_field.output[1]`). It just makes it easier to read.
- just an fyi that I think the best practice is to put [logic like this](https://github.com/LiterallyUniqueLogin/ukbiobank_strs/pull/1/files?diff=unified&w=0#diff-6c0c4fb57b3df01ca1ec0d8dffcdd1e24e77f0d7f3414a7ca430364d365949acL187-L189) into a `param` and use a `shell` directive instead of a `run` directive. In general, the best practice is to make snakemake aware of everything that could possibly change the output of your rules. And often the best way to do that for things like this is to declare those as `param`s. This seems like something that you tend to do a lot, so I wouldn't recommend completely overhauling your code over this, but it might be something to consider when you write new rules.
    One example of a benefit to doing this is that you can easily trigger reruns for jobs where a `param` value changes via the command line. So, using [that example that I linked](https://github.com/LiterallyUniqueLogin/ukbiobank_strs/pull/1/files?diff=unified&w=0#diff-6c0c4fb57b3df01ca1ec0d8dffcdd1e24e77f0d7f3414a7ca430364d365949acL187-L189), if something changes within the code that decides whether a phenotype is binary (ie `phenotypes.is_binary()`), you could easily rerun the jobs where the output of `is_binary()` has changed. This gets useful when your rules have a lot of `param`s. Another benefit is that you can easily view the shell commands when you do a dry-run to check that they were composed correctly. And yet another benefit is that the params are resolved prior to job submission, so you can get immediate feedback on any assertions that you have within that logic without having to wait for the job to get executed.
    Note that if you already have a bunch of logic to decide what the `param`s are, and you don't want to separate that logic into distinct parts for each `param`, you could just put all of that logic into a function that outputs a dictionary of `param` values and then pass that function to `param:`

**Comment by aryarm** [comment]
Ok, so turns out I actually wasn't able to use GitHub's code review feature, after all. I can only comment on areas within the diff, and since the commits in this PR didn't change all of the lines in the file, I could comment on those lines.

So instead, I just hyperlinked to them from within that big comment block.

**Comment by LiterallyUniqueLogin** [comment]
Thanks for the comments!!

> * is it possible for [a phenotype field name to include an underscore](https://github.com/LiterallyUniqueLogin/ukbiobank_strs/blob/886286601c001f7c4253348e96cecb6102fed1ad/workflow/snakefile#L62)? if so, you might have problems when you separate your wildcards by underscores. You can minimize the risk of wildcards getting misunderstood by separating your wildcards with `/`, `.`, or `-`.

Yes, I just noticed this independently. The field ID is numeric, so I restricted it to that. This should solve the ambiguity for this rule. (It actually worked without this because the capture groups are greedy, but being explicit is better of course).
 
>     * just my personal preference: I like to use `expand()` and `rules.rulename.output` whenever possible. I think it makes for cleaner code, makes it easier to understand at a glance when I'm referring to the output of a different rule, and makes it clear how my variables get translated into wildcards. For example, [this section](https://github.com/LiterallyUniqueLogin/ukbiobank_strs/blob/886286601c001f7c4253348e96cecb6102fed1ad/workflow/snakefile#L81-L85) could instead be
>       ```
>           fields.extend(
>               expand(
>                   rules.decompress_field.output[0], zip, 
>                   field_name = ['year_of_birth', 'month_of_birth', 'date_of_death'],
>                   field_id = ['34', '52', '40000']
>               )
>           )
>       ```
>           
>       It might not improve the clarity of the code as much in this specific example, but it might be something to consider for more complicated situations in which you have lots of wildcards and lots of variables.

Agreed. I've been using that since you mentioned it to me.

>     * By the way, it seems like you're already starting to do this, but I would just recommend [naming all of your input and output files](https://snakemake.readthedocs.io/en/stable/snakefiles/rules.html) so that you can access them by their name keyword (ex: `rules.decompress_field.output.readme` instead of `rules.decompress_field.output[1]`). It just makes it easier to read and reduces work for you later down the road if you ever change the order of the input or output files.

Yep, doing so to new rules and as I go back and touch old ones.

>     * just an fyi that I think the best practice is to put [logic like this](https://github.com/LiterallyUniqueLogin/ukbiobank_strs/blob/886286601c001f7c4253348e96cecb6102fed1ad/workflow/snakefile#L187-L189) into a `param` and use a `shell` directive instead of a `run` directive. In general, the best practice is to make snakemake aware of everything that could possibly change the output of your rules. And often the best way to do that for things like this is to declare those as `param`s. This seems like something that you tend to do a lot, so I wouldn't recommend completely overhauling your code over this, but it might be something to consider when you write new rules.
>       One example of a benefit to doing this is that you can easily trigger reruns for jobs where a `param` value changes via the command line. So, using [that example that I linked](https://github.com/LiterallyUniqueLogin/ukbiobank_strs/blob/886286601c001f7c4253348e96cecb6102fed1ad/workflow/snakefile#L187-L189), if something changes within the code that decides whether a phenotype is binary (ie `phenotypes.is_binary()`), you could easily rerun the jobs where the output of `is_binary()` has changed. This gets useful when your rules have a lot of `param`s. Another benefit is that you can easily view the shell commands when you do a dry-run to check that they were composed correctly. And yet another benefit is that the params are resolved prior to job submission, so you can get immediate feedback on any assertions that you have within that logic without having to wait for the job to get executed.
>       Note that if you already have a bunch of logic to decide what the `param`s are, and you don't want to separate that logic into distinct parts for each `param`, you could just put all of that logic into a function that outputs a dictionary of `param` values and then pass that function to `param:`

I didn't get the point of `params` the first time I came across them in the snakemake docs, and I'm still not sure of their worth even after reading what you wrote.
Pros
* Display of shell commands during graph building. 
* Checking of assertions during graph building.

Cons:
* Rerunning jobs when parameters change. Is this the same as inputs, where if the last run of a job that created an output has a different value for a parameter as an input, then the job is rerun? So far the only use case I've seen for parameters is cleaning up shell scripts, not actually defining input. So as far as I can currently see, this is a downside.
* Unnecessary complication. This is another place to define how a job works, but as far as I can tell it doesn't add anything more than minor debugging functionality - to my understanding parameters can be replaced by variables in the `run` block to the same effect.

Thoughts?

**Comment by aryarm** [comment]
> * Rerunning jobs when parameters change. Is this the same as inputs, where if the last run of a job that created an output has a different value for a parameter as an input, then the job is rerun? So far the only use case I've seen for parameters is cleaning up shell scripts, not actually defining input. So as far as I can currently see, this is a downside.

Yes, the idea is that you can redo the jobs that have parameter values that have changed via [the command line like this](https://snakemake.readthedocs.io/en/stable/project_info/faq.html#how-do-i-trigger-re-runs-for-rules-with-updated-code-or-parameters). But I agree that you wouldn't use `params:` to define input. You use it to tell Snakemake about other variables that may alter how the rule gets run.

> * Unnecessary complication. This is another place to define how a job works, but as far as I can tell it doesn't add anything more than minor debugging functionality - to my understanding parameters can be replaced by variables in the run block to the same effect.

imo, I think the unnecessary complication bit is a little subjective. But yes, I think it would be extra work to redo rules you've already written to make them align with this paradigm, so I'm not suggesting you do that.
But let's say that you have a rule that you've implemented like this:
```
rule A:
    input: ...
    output: ...
    run:
        [lots of code to define var1 and var2]
        shell(f"cmd {var1} {var2}")
```
then the equivalent would be
```
def rule_A_params(wildcards):
    [lots of code to define var1 and var2]
    return {'var1': var1, 'var2': var2}

rule A:
    input: ...
    params: rule_A_params
    output: ...
    shell:
        "cmd {params.var1} {params.var2}"
```
which, admittedly, is a bit more boilerplate. It's up to you whether it's worth it; I'm not going to tell you that it is. I just wanted to make sure you were aware of the pros and cons, and it seems like you are.

**Pull request closed without merging**
